import type { Metadata } from "next";
import "../styles/globals.css";
import React from "react";
import {Providers} from "@/app/providers";
import {cn} from "@/lib/utils";
import {geist} from "@/styles/fonts";

export const metadata: Metadata = {
  title: "academic-analysis-system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={cn("font-geist antialiased", geist.variable)}>
      <main className="max-w-5xl px-8 py-6 mx-auto">
          <Providers>
              {children}
          </Providers>
      </main>
      </body>
      </html>
  );
}
